CREATE OR REPLACE PROCEDURE proc_create_client_compte() AS $$
BEGIN
  --créer la table client
  CREATE TABLE IF NOT EXISTS client (
    client_id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 1),
    nom VARCHAR(50) NOT NULL,
    CONSTRAINT pk_client_id PRIMARY KEY (client_id));

  --créer la table compte
  CREATE TABLE IF NOT EXISTS compte (
    compte_id int GENERATED ALWAYS AS IDENTITY,
    client_id int NOT NULL,
    montant decimal(10,2) NOT NULL DEFAULT 0,
    CONSTRAINT pk_compte_id PRIMARY KEY (compte_id),
    CONSTRAINT fk_compte_client_id FOREIGN KEY (client_id) REFERENCES client(client_id),
    CONSTRAINT ch_compte_montant CHECK (montant >= 0));

  --insérer les données dans la table client
  INSERT INTO client VALUES (1, 'John'),
    (2, 'Jane');

  --insérer les données dans la table compte
  INSERT INTO compte (client_id, montant) VALUES (1, DEFAULT),
    (2, 200);
END;
$$ LANGUAGE plpgsql;